name: EasySetSpawn
main: me.clickpt.easysetspawn.Main
version: 3.0
author: ClickPT

commands:
    setspawn:
     description: Set spawn.
    spawn:
     description: Teleport to spawn.
    easyss:
     description: General command.