name: EasySetSpawn
main: me.clickpt.easysetspawn.Main
version: 3.2
author: ClickPT
website: https://dev.bukkit.org/projects/easysetspawn

commands:
    setspawn:
     description: Set spawn.
    spawn:
     description: Teleport to spawn.
    easyss:
     description: General command.