name: EasySetSpawn
main: me.clickpt.easysetspawn.Main
version: 2.0
author: ClickPT

commands:
    setspawn:
     description: Set spawn.
    spawn:
     description: Teleport to spawn.
    ess:
     description: General command.